import React, {useEffect} from 'react'
import Router from 'next/router';
import Head from 'next/head'
import styles from '../styles/Home.module.css'


export default function Home() {


  // redirect user to home page
  useEffect(() => {
    Router.push('/home')
  }) 


  return (
    <>
    
    <div className={styles.container}>
      <Head>
        <title>One RC</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>Index Page</main>
      
      

      <footer className={styles.footer}>
        One Rupee Club
      </footer>
    </div>
    </>
      
  )
}
